### ISSUE TITLE
Won't start on Windows 10

### ISSUE THREAD

**Issue by kellewic** [dlebansais/PgJsonParse#1]
Every time I try to start the program, it dies with "PgJsonParse has stopped working" window. No specific reason given. I eventually got it to download the JSON files, but it gets to about 90% "parsing" and dies.

![clipboard01](https://user-images.githubusercontent.com/3178267/39390434-51ded6a8-4a49-11e8-874c-866050a20206.jpg)

**Comment by dlebansais** [comment]
I assume the issue has been resolved at some point.
