### ISSUE TITLE
Item stats not updating correctly

### ISSUE THREAD

**Issue by Telixnth** [dlebansais/PgJsonParse#3]
In Advanced Search mode, when switching from one piece of armor to another, the item name, description, and icon will update appropriately, but all other values 'stick' and do not update to the new item. Example: clicking on Amazing Bard Boots and then Amazing Cloth Pants will list the cloth pants as having +78 armor, chance to evade projectiles, keywords 'Leather Armor', etc.

Reproduction steps are as follows:

1. Click an item, it loads correctly
2. Click on a second item, the values will all stick with the previous item
3. Click on a third item, the values will load correctly again
4. Values will then stick again, repeating this pattern

**Comment by dlebansais** [comment]
Thanks for the report! With this info I was able to reproduce the bug introduced in the last release and fix it. You can find the fix in v321.2.
