### ISSUE TITLE
pgbuilder error

### ISSUE THREAD

**Issue by benaniel** [dlebansais/PgJsonParse#5]
control burn deals 366 indirect fire damage over 12 seconds
agression deterrent ignites all tagets , dealing 260 fire damage over 8 seconds
cow's bash inflict bugs on the target dealing 310 nature damage over 10 seconds
tough Hoof activation healing + 48
![astoundingcombatstaff](https://user-images.githubusercontent.com/50747562/81637343-5dac8480-9416-11ea-8ee6-40d5a5f22515.jpg)

**Comment by dlebansais** [comment]
Merci, c'est fixé. Dispo dans la prochaine version.

**Comment by benaniel** [comment]
Pb avec 3 mods warden
ring : conditionnal shock deals + 66 ans reuse is 2 sec sooner : l'outil indique 2 secondes de plusboot : privacy field deals + 61 damage and the first melee attacker is knocked out : l outil ajoute les degats aux degats de feu qu un autre mod a place , le ko est pas mentionne par l outilgants conditionnal shock causes the target to suffer + 20% degat de feu pas mentionne par l outil
    Le mercredi 13 mai 2020 à 12:14:54 UTC+2, David Le Bansais <notifications@github.com> a écrit :  
 
 


Closed #5.

**Comment by dlebansais** [comment]
Pour les deux derniers il me faudrait un screenshot des abilities. Idéalement, un fichier build (.txt) et les screenshots qui vont avec.

**Comment by benaniel** [comment]
le fichier txt , je peux le saisir moi meme avec les abilities ou faut faire une manip ?    Le samedi 16 mai 2020 à 15:51:21 UTC+2, David Le Bansais <notifications@github.com> a écrit :  
 
 


Pour les deux derniers il me faudrait un screenshot des abilities. Idéalement, un fichier build (.txt) et les screenshots qui vont avec.

**Comment by benaniel** [comment]
Le samedi 16 mai 2020 à 15:56:56 UTC+2, Jean Yves Moysan <jeanyves.moysan@yahoo.fr> a écrit :  
 
  
le fichier txt , je peux le saisir moi meme avec les abilities ou faut faire une manip ?    Le samedi 16 mai 2020 à 15:51:21 UTC+2, David Le Bansais <notifications@github.com> a écrit :  
 
 


Pour les deux derniers il me faudrait un screenshot des abilities. Idéalement, un fichier build (.txt) et les screenshots qui vont avec.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
    
"Build": {
	"Skill1": "Cow",
	"Skill2": "Warden",
	"LoreLevel": 27,
	"IsFairyCharacter": false,
	"Ability_0_0": "ability_6122",
	"Ability_0_1": "ability_6120",
	"Ability_0_2": "ability_6116",
	"Ability_0_3": "ability_6118",
	"Ability_0_4": "ability_6117",
	"Ability_0_5": "ability_6119",
	"Ability_1_0": "ability_7315",
	"Ability_1_1": "ability_7236",
	"Ability_1_2": "ability_7221",
	"Ability_1_3": "ability_7280",
	"Ability_1_4": "ability_7265",
	"Ability_1_5": "ability_7360",
	"Main Hand": {
		"Item": "item_47129",
		"Enhancement": [
			0,
			0,
			0,
			0,
			0,
			0
		],
		"Power_0": "power_27112",
		"PowerTier_0": 15,
		"Power_1": "power_27192",
		"PowerTier_1": 15,
		"Power_2": "power_20014",
		"PowerTier_2": 15,
		"Power_3": "power_20301",
		"PowerTier_3": 15,
		"Power_4": "power_27071",
		"PowerTier_4": 15,
		"Power_5": "power_20354",
		"PowerTier_5": 15,
		"Power_6": "power_27051",
		"PowerTier_6": 15
	},
	"Off Hand": {
		"Item": "item_45042",
		"Enhancement": [
			0,
			0,
			0,
			0,
			0,
			0
		],
		"Power_0": "power_20044",
		"PowerTier_0": 15,
		"Power_1": "power_27132",
		"PowerTier_1": 15,
		"Power_2": "power_27056",
		"PowerTier_2": 15,
		"Power_3": "power_20354",
		"PowerTier_3": 15,
		"Power_4": "power_27191",
		"PowerTier_4": 15
	},
	"Head": {
		"Item": "item_44029",
		"Enhancement": [
			0,
			0,
			0,
			0,
			0,
			0
		],
		"Power_0": "power_20202",
		"PowerTier_0": 15,
		"Power_1": "power_27115",
		"PowerTier_1": 15,
		"Power_2": "power_27051",
		"PowerTier_2": 15,
		"Power_3": "power_27001",
		"PowerTier_3": 7,
		"Power_4": "power_20001",
		"PowerTier_4": 7
	},
	"Chest": {
		"Item": "item_42109",
		"Enhancement": [
			0,
			0,
			0,
			0,
			0,
			0
		],
		"Power_0": "power_27113",
		"PowerTier_0": 15,
		"Power_1": "power_20065",
		"PowerTier_1": 7,
		"Power_2": "power_27134",
		"PowerTier_2": 15,
		"Power_3": "power_27156",
		"PowerTier_3": 15
	},
	"Legs": {
		"Item": "item_41049",
		"Enhancement": [
			0,
			0,
			0,
			0,
			0,
			0
		],
		"Power_0": "power_27135",
		"PowerTier_0": 15,
		"Power_1": "power_27055",
		"PowerTier_1": 15,
		"Power_2": "power_27111",
		"PowerTier_2": 15,
		"Power_3": "power_20015",
		"PowerTier_3": 15
	},
	"Feet": {
		"Item": "item_40029",
		"Enhancement": [
			0,
			0,
			0,
			0,
			0,
			0
		],
		"Power_0": "power_27132",
		"PowerTier_0": 15,
		"Power_1": "power_27073",
		"PowerTier_1": 15,
		"Power_2": "power_20061",
		"PowerTier_2": 15,
		"Power_3": "power_20043",
		"PowerTier_3": 15,
		"Power_4": "power_27152",
		"PowerTier_4": 15
	},
	"Hands": {
		"Item": "item_43029",
		"Enhancement": [
			0,
			0,
			0,
			0,
			0,
			0
		],
		"Power_0": "power_27192",
		"PowerTier_0": 15,
		"Power_1": "power_27052",
		"PowerTier_1": 15,
		"Power_2": "power_20063",
		"PowerTier_2": 7,
		"Power_3": "power_20061",
		"PowerTier_3": 15,
		"Power_4": "power_27071",
		"PowerTier_4": 15
	},
	"Neck": {
		"Item": "item_48148",
		"Enhancement": [
			0,
			0,
			0,
			0,
			0,
			0
		],
		"Power_0": "power_27001",
		"PowerTier_0": 7,
		"Power_1": "power_20001",
		"PowerTier_1": 7,
		"Power_2": "power_27133",
		"PowerTier_2": 15,
		"Power_3": "power_20201",
		"PowerTier_3": 15,
		"Power_4": "power_20353",
		"PowerTier_4": 15,
		"Power_5": "power_27056",
		"PowerTier_5": 15
	},
	"Ring": {
		"Item": "item_49118",
		"Enhancement": [
			0,
			0,
			0,
			0,
			0,
			0
		],
		"Power_0": "power_27156",
		"PowerTier_0": 15,
		"Power_1": "power_27053",
		"PowerTier_1": 15,
		"Power_2": "power_20042",
		"PowerTier_2": 15,
		"Power_3": "power_27131",
		"PowerTier_3": 15,
		"Power_4": "power_20007",
		"PowerTier_4": 15,
		"Power_5": "power_27111",
		"PowerTier_5": 15
	},
	"Racial": {
		"Item": "item_50008",
		"Enhancement": [
			0,
			0,
			0,
			0,
			0,
			0
		]
	},
	"Waist": {
		"Item": "item_54101",
		"Enhancement": [
			0,
			0,
			0,
			0,
			0,
			0
		]
	}
}

**Comment by dlebansais** [comment]
Merci pour le fichier, ça passe. Mais pour Conditioning Shock, sans le screenshot je peux rien faire. Tu peux joindre des fichiers sur GitHub normalement (ou par email).

**Comment by benaniel** [comment]
Il faut un screenshots du jeu , pas de l outil ?

Envoyé depuis Yahoo Mail pour Android 
 
  Le sam., mai 16, 2020 à 18:26, David Le Bansais<notifications@github.com> a écrit :   


Merci pour le fichier, ça passe. Mais pour Conditioning Shock, sans le screenshot je peux rien faire. Tu peux joindre des fichiers sur GitHub normalement (ou par email).

**Comment by benaniel** [comment]
Le samedi 16 mai 2020 à 18:26:29 UTC+2, David Le Bansais <notifications@github.com> a écrit :  
 
 


Merci pour le fichier, ça passe. Mais pour Conditioning Shock, sans le screenshot je peux rien faire. Tu peux joindre des fichiers sur GitHub normalement (ou par email).
